### PR TITLE
Link to updated example dapp

### PR DESCRIPTION
**Pull request by lukaw3d**

### CODE REVIEW

**Comment by pro-wh** [comment]
https://github.com/bitcat365/oasis-test-dapp/pull/1 closed by author :thinking:

**Comment by pro-wh** [comment]
could we have the repo owned by the foundation

**Comment by lukaw3d** [comment]
yep, I'd prefer that (although code isn't up to standards)

**Review by pro-wh — APPROVED** [review]
:shrug: :+1:

**Pull request merged**
