### PR TITLE
Fix displaying grpc-message on error

### PR DESCRIPTION
**Pull request by lukaw3d**
Related to https://github.com/oasisprotocol/oasis-wallet-ext/pull/168

| Before | After |
| --- | --- |
|   |   |

### CODE REVIEW

**Review by pro-wh — COMMENTED** [review]
is there any hope of getting the error sources to be consistent instead of doing all these `||`s, that would be, what's that word, more good.

this though, is good. two things though

1. are there really errors with .metadata['grpc-message'] that don't have .message set correctly? we should fix that in oasis-sdk
2. in oasis-sdk we'll be changing errors from the client soon in a way that breaks this. you'll probably need something like `.cause.metadata[...]`

**Comment by lukaw3d** [comment]
Maybe https://github.com/oasisprotocol/oasis-wallet-ext/pull/174/commits/6da4d492d82789a7cda0a5e131202f5f5815e06b was the inconsistency :shrug:

**Review by pro-wh — APPROVED** [review]
oh gosh that's really how most places in this codebase do it

**Comment by lukaw3d** [comment]
`.message` seems to be missing but not because of sdk. If `.message` was there, should it take priority:?
```js
let errMessage =
  data?.message ||
  data?.error?.message ||
  data?.error?.metadata?.['grpc-message'] ||
  getLanguage('postFailed')
```

**Comment by lukaw3d** [comment]
Probably

**Pull request merged**
