### PR TITLE
Avoid XSS via translations #10

### LINKED ISSUE #10: Avoid XSS via translations
Blocks https://github.com/oasisprotocol/oasis-wallet-ext/issues/1

Avoid `dangerouslySetInnerHTML` for translations. Use [Trans component](https://react.i18next.com/latest/trans-component) instead.
https://github.com/oasisprotocol/oasis-wallet-ext/blob/dabb8b41c105b86bf7e526916541e9db9dc98d0c/src/popup/component/LedgerConnected/index.js#L37

(Note: [CSP](https://github.com/oasisprotocol/oasis-wallet-ext/blob/f912f132cc22bec5d70541ddf46b90d7d28c6c6d/public/manifest.json#L35) should prevent XSS attacks, but this still adds unnecessary risk)

### PR DESCRIPTION
**Pull request by lvshaoping007**
[#10 ] ledger text style change to fix #10

### CODE REVIEW

**Review by pro-wh — CHANGES_REQUESTED** [review]
This has changes from other PRs mixed in. Requesting changes to remove those unrelated commits.

@lukaw3d and @lvshaoping007, you two were discussing the alternative of using a i18next Trans component instead of creating this custom one. Have you come to a conclusion on that, or what's the latest?

**Comment by tjanez** [comment]
> This has changes from other PRs mixed in. Requesting changes to remove those unrelated commits.

:+1:

**Comment by lukaw3d** [comment]
This whole PR should just be four lines
```diff
- "And <b>do not close</b> this window."
+ "And <strong>do not close</strong> this window."
- "在此之前<b>请勿关闭</b>此窗口。"
+ "在此之前<strong>请勿关闭</strong>此窗口。"

+ import { Trans } from 'react-i18next'
- <p className="wallet-tip-description" key={tip} dangerouslySetInnerHTML={{ __html: getLanguage(tip) }} />
+ <p className="wallet-tip-description" key={tip}><Trans i18nKey={tip}></Trans></p>
```

**Comment by lvshaoping007** [comment]
> 整个 PR 应该只有四行
> 
> ```diff
> - “并且<b>不要关闭</b>这个窗口。” 
> + "并且<strong>不要关闭</strong>这个窗口。" 
> - "在此之前<b>请勿关闭</b>此窗口。" 
> + "在此之前<strong>请勿关闭</strong>此窗口。"
> 
> + import { Trans } from 'react-i18next' 
> - <p className="wallet-tip-description" key={tip} risklySetInnerHTML={{ __html: getLanguage(tip) }} /> 
> + <p className="wallet- tip-description" key={tip}><Trans i18nKey={tip}></Trans></p>
> ```

yes , this contain other PR before , so i will close this

**Pull request closed without merging**
