### PR TITLE
fix lockPage password issue

### PR DESCRIPTION
**Pull request by lvshaoping007**
fix lock page password input error #158

### CODE REVIEW

**Review by pro-wh — APPROVED** [review]
fixes #158 

previously, trimming on every input event would delete spaces that go into the middle of a password, because the part that came after wouldn't be typed yet. this PR moves the trimming to a single operation at the end.

I suppose the trimming overall is still good, in case people are copying from a password manager and accidentally select some extra whitespace

**Comment by pro-wh** [comment]
I'm going to rebase and merge

**Comment by lukaw3d** [comment]
I wouldn't trim

All trimmed characters:
```
new Array(65545).fill(0).map((z, ix) => [ix, String.fromCharCode(ix)]).filter(([ix, char]) => char !== char.trim())
[9, '\t']
[10, '\n']
[11, '\v']
[12, '\f']
[13, '\r']
[32, ' ']
[160, ' ']
[5760, ' ']
[8192, ' ']
[8193, ' ']
[8194, ' ']
[8195, ' ']
[8196, ' ']
[8197, ' ']
[8198, ' ']
[8199, ' ']
[8200, ' ']
[8201, ' ']
[8202, ' ']
[8232, ' ']
[8233, ' ']
[8239, ' ']
[8287, ' ']
[12288, '　']
[65279, '﻿']
```

**Comment by pro-wh** [comment]
do we want to preserve some of those?

**Comment by lukaw3d** [comment]
All of them :D

**Comment by pro-wh** [comment]
filed as #186 :slightly_smiling_face:

**Pull request merged**
